version: "3.3"

services:
  audiobox-advent-calendar-cron:
    image: "ghcr.io/svendroid/audiobox-advent-calendar-cron:latest"
    restart: unless-stopped
    container_name: audiobox-advent-calendar
    volumes:
      - ./config:/config
      - ./audioFiles:/audioFiles