name: Build & publish latest image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build application
        run: ./gradlew assembleDist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: audiobox-advent-calendar
          path: build/distributions/*.tar

  standalone_image:
    name: Build Docker image standalone
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: audiobox-advent-calendar
          path: build/distributions/

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/svendroid/audiobox-advent-calendar-standalone:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/audiobox-advent-calendar-standalone.Dockerfile
          push: true
          tags: ghcr.io/svendroid/audiobox-advent-calendar:standalone
          labels: ${{ steps.docker_meta.outputs.labels }}

  cron_image:
    name: Build Docker image cron
    runs-on: ubuntu-latest
    needs:
      - standalone_image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: audiobox-advent-calendar
          path: build/distributions/

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/svendroid/audiobox-advent-calendar-cron:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/audiobox-advent-calendar-cron.Dockerfile
          push: true
          tags: ghcr.io/svendroid/audiobox-advent-calendar:cron
          labels: ${{ steps.docker_meta.outputs.labels }}
